import { promises as fs } from "node:fs";
import { statSync } from "node:fs";
import path from "node:path";
import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import { createDefaultConfig, readConfig, writeConfigAtomic, type Architecture, type Backend, type OpenCraftConfig, type PackageManager, type Storage } from "@antihero/config";
import { applyFiles, loadRegistry, planInstall, updateEnvExample, type InstallPlan } from "@antihero/registry";
import { detectPackageManager, packageCommand, pathExists } from "@antihero/shared";

export interface CreateOptions { projectName:string; directory:string; architecture:Architecture; backend:Backend; auth:"none"|"google"; storage:Storage; modules:string[]; packageManager:PackageManager; install:boolean; git:boolean; dryRun:boolean; yes:boolean }
function findRepositoryRoot(): string { let current=path.dirname(fileURLToPath(import.meta.url)); for(let i=0;i<8;i++){if(requireExists(path.join(current,"templates/nextjs-base"))&&requireExists(path.join(current,"registry/modules")))return current;current=path.dirname(current)} throw new Error("OpenCraft templates are missing from this package"); }
function requireExists(target:string){try{return Boolean(statSync(target))}catch{return false}}
function moduleNames(options:Pick<CreateOptions,"backend"|"auth"|"storage"|"modules">):string[]{const names=[...options.modules];if(options.backend!=="none")names.push(`auth-${options.backend}`);if(options.auth==="google")names.push("google-auth");if(options.storage!=="none")names.push(`storage-${options.storage}`);return [...new Set(names)]}
export function validateChoices(options:Pick<CreateOptions,"backend"|"auth"|"storage"|"modules">):void{if(options.storage==="supabase"&&options.backend!=="supabase")throw new Error("Supabase Storage requires the Supabase backend");if(options.storage==="firebase"&&options.backend!=="firebase")throw new Error("Firebase Storage requires the Firebase backend");if(options.auth==="google"&&options.backend==="none")throw new Error("Google authentication requires Supabase or Firebase");if(options.modules.some((module)=>module==="image-upload"||module==="file-upload")&&options.storage==="none")throw new Error("Image/file upload requires a storage provider")}
async function copyTemplate(source:string,target:string,replacements:Record<string,string>):Promise<string[]>{const created:string[]=[];for(const entry of await fs.readdir(source,{withFileTypes:true})){const from=path.join(source,entry.name);const to=path.join(target,entry.name);if(entry.isDirectory()){created.push(...await copyTemplate(from,to,replacements));continue}await fs.mkdir(path.dirname(to),{recursive:true});let content=await fs.readFile(from,"utf8");for(const[token,value]of Object.entries(replacements))content=content.replaceAll(`{{${token}}}`,value);await fs.writeFile(to,content);created.push(to)}return created}
async function createArchitecture(root:string,architecture:Architecture,repositoryRoot:string){const data=JSON.parse(await fs.readFile(path.join(repositoryRoot,"registry/architectures",`${architecture}.json`),"utf8")) as {directories:string[]};await Promise.all(data.directories.map((directory)=>fs.mkdir(path.join(root,directory),{recursive:true})));}
export function renderAgents(config:OpenCraftConfig):string{const modules=Object.keys(config.modules);return `# AGENTS.md\n\nStack: Next.js App Router, TypeScript strict, Tailwind CSS, shadcn/ui. Architecture: ${config.architecture}. Backend: ${config.backend.provider}. Authentication: ${config.authentication.provider} (${config.authentication.methods.join(", ")||"none"}). Storage: ${config.storage.provider}.\n\n- Keep shadcn primitives in src/components/ui.\n- Place business-specific code ${config.architecture==="atomic"?"near its route; reusable presentation components follow atomic layers":"inside src/features and export cross-feature APIs through index.ts"}.\n- Put provider SDKs in src/infrastructure and use installed adapters.\n- Build Route Handlers only under src/app/api/**/route.ts.\n- Validate every external input on the server with Zod; client validation is only UX.\n- Never trust client-side authorization. Verify authentication, role, and resource ownership server-side.\n- Never concatenate user input into SQL or accept arbitrary Firestore collection, field, or operators.\n- Validate upload signature, MIME, size, dimensions, filename/key, and authorization; reject SVG by default.\n- Reuse installed modules before creating abstractions. Do not change architecture without approval.\n- Never log secrets, tokens, cookies, or raw sensitive payloads.\n- Installed modules: ${modules.join(", ")||"none"}.\n- Verify with: ${config.packageManager} run lint; ${config.packageManager} run type-check; ${config.packageManager} run test; ${config.packageManager} run build.\n`}
async function mergeDependencies(root:string,plan:InstallPlan){const target=path.join(root,"package.json");const pkg=JSON.parse(await fs.readFile(target,"utf8")) as {dependencies?:Record<string,string>;devDependencies?:Record<string,string>};pkg.dependencies={...pkg.dependencies,...plan.dependencies};pkg.devDependencies={...pkg.devDependencies,...plan.devDependencies};await fs.writeFile(target,`${JSON.stringify(pkg,null,2)}\n`)}
async function run(command:string,args:string[],cwd:string):Promise<void>{await new Promise<void>((resolve,reject)=>{const child=spawn(command,args,{cwd,stdio:"inherit"});child.on("error",reject);child.on("exit",(code)=>code===0?resolve():reject(new Error(`${command} exited with ${code??"unknown"}`)))})}
export function printPlan(plan:InstallPlan):string{return [`Modules: ${plan.modules.map((item)=>item.manifest.name).join(", ")||"none"}`,`Files:\n${plan.files.map((file)=>`  ${file.status.padEnd(9)} ${file.target}`).join("\n")||"  none"}`,`Dependencies: ${Object.keys(plan.dependencies).join(", ")||"none"}`,`Dev dependencies: ${Object.keys(plan.devDependencies).join(", ")||"none"}`,`Environment: ${plan.environmentVariables.join(", ")||"none"}`].join("\n")}
export async function addModules(root:string,names:string[],options:{dryRun?:boolean;yes?:boolean;overwrite?:boolean;install?:boolean}={}):Promise<InstallPlan>{let config=await readConfig(root);const repositoryRoot=findRepositoryRoot();process.env.OPENCRAFT_REGISTRY=path.join(repositoryRoot,"registry");const registry=await loadRegistry();const expanded=[...names];if((names.includes("image-upload")||names.includes("file-upload"))&&config.storage.provider!=="none")expanded.push(`storage-${config.storage.provider}`);const plan=await planInstall(root,expanded,config,registry);if(options.dryRun)return plan;if(plan.files.some((file)=>file.status==="modified")&&!options.overwrite)throw new Error("Modified files would be overwritten. Run `opencraft diff <module>` and use explicit overwrite only after review.");await applyFiles(plan,options.overwrite);await mergeDependencies(root,plan);await updateEnvExample(root,plan.environmentVariables);for(const item of plan.modules)config={...config,modules:{...config.modules,[item.manifest.name]:{version:item.manifest.version,files:Object.fromEntries(plan.files.filter((file)=>file.source.startsWith(item.directory)).map((file)=>[path.relative(root,file.target),file.checksum]))}}};await writeConfigAtomic(root,config);await fs.writeFile(path.join(root,"AGENTS.md"),renderAgents(config));if(options.install){const command=packageCommand(config.packageManager,"install");await run(command[0]!,command.slice(1),root)}return plan}
export async function createProject(options:CreateOptions):Promise<{files:string[];plan:InstallPlan}>{validateChoices(options);const repositoryRoot=findRepositoryRoot();const target=path.resolve(options.directory);if(await pathExists(target)&&(await fs.readdir(target)).length)throw new Error(`Target directory is not empty: ${target}`);const config=createDefaultConfig({architecture:options.architecture,packageManager:options.packageManager,backend:{provider:options.backend},authentication:{provider:options.auth==="google"?options.backend:"none",methods:options.auth==="google"?["google"]:[]},storage:{provider:options.storage}});const registry=await loadRegistry(path.join(repositoryRoot,"registry"));const names=moduleNames(options);const emptyRoot=target;const plan=await planInstall(emptyRoot,names,config,registry);if(options.dryRun)return{files:[],plan};await fs.mkdir(target,{recursive:true});const files=await copyTemplate(path.join(repositoryRoot,"templates/nextjs-base"),target,{projectName:options.projectName,runCommand:options.packageManager});await createArchitecture(target,options.architecture,repositoryRoot);await writeConfigAtomic(target,config);await fs.writeFile(path.join(target,"AGENTS.md"),renderAgents(config));await addModules(target,names,{yes:true,install:false});if(options.install){const command=packageCommand(options.packageManager,"install");await run(command[0]!,command.slice(1),target)}if(options.git)await run("git",["init"],target);return{files,plan}}
export async function initProject(root:string,architecture:Architecture):Promise<OpenCraftConfig>{if(!await pathExists(path.join(root,"src/app"))&&!await pathExists(path.join(root,"app")))throw new Error("Next.js App Router was not detected");if(!await pathExists(path.join(root,"tsconfig.json")))throw new Error("TypeScript was not detected");const config=createDefaultConfig({architecture,packageManager:await detectPackageManager(root)});await writeConfigAtomic(root,config);await fs.writeFile(path.join(root,"AGENTS.md"),renderAgents(config));return config}
export async function doctor(root:string):Promise<string[]>{const issues:string[]=[];let config:OpenCraftConfig;try{config=await readConfig(root)}catch(error){return[`Invalid or missing opencraft.config.json: ${error instanceof Error?error.message:"unknown error"}`]}if(!await pathExists(path.join(root,"src/app"))&&!await pathExists(path.join(root,"app")))issues.push("Next.js App Router directory is missing");const pkg=JSON.parse(await fs.readFile(path.join(root,"package.json"),"utf8")) as {dependencies?:Record<string,string>};const registry=await loadRegistry(path.join(findRepositoryRoot(),"registry"));for(const[name,state]of Object.entries(config.modules)){const item=registry.get(name);if(!item){issues.push(`Installed module is absent from registry: ${name}`);continue}for(const[file,expected]of Object.entries(state.files)){if(!await pathExists(path.join(root,file)))issues.push(`Missing module file: ${file}`);else if(expected==="")issues.push(`Missing checksum for: ${file}`)}for(const dependency of Object.keys(item.manifest.npmDependencies))if(!pkg.dependencies?.[dependency])issues.push(`Missing dependency: ${dependency}`);for(const variable of item.manifest.environmentVariables)if(variable.required&&!process.env[variable.name])issues.push(`Environment variable unavailable: ${variable.name}`)}return issues}
